Specify platform of PostGIS Docker image (#2368)
On macOS, we get this error because PostGIS doesn't provide Docker image
for macOS.

```
❯ just start
docker-compose up -d fileserver
[+] Running 1/1
 ✔ Container martin-fileserver-1  Running                                                                                                    0.0s
docker-compose up -d db
[+] Running 0/1
 ⠴ db Pulling                                                                                                                                4.5s
no matching manifest for linux/arm64/v8 in the manifest list entries
error: Recipe `docker-up` failed on line 496 with exit code 1
```

This happens because Docker chooses the same platform as the host by
default. This pull request fixes it by specifying`linux/x86_64` platform
for these images explicitly.