chore(ci): retry in initdb.sh (#2473)
I think this fixes an intermittent CI flake:

```
################################################################################################
Loading Martin test fixtures into '***localhost:34837/test?sslmode=require'
################################################################################################
psql: error: connection to server at "localhost" (::1), port 34837 failed: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
Error: Process completed with exit code 2.

---------

Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>