docs(dev-guide): Add some note about alternative Docker hosts/runtimes (#2388)
I get this error when I tried to run `cargo test`, and found this is
because I use an alternative Docker host (Colima), which locates its
docker socket on a different location
(`${HOME}/.colima/default/docker.sock`).

```
failures:

---- tiles::postgres::pool::tests::parse_version stdout ----

thread 'tiles::postgres::pool::tests::parse_version' (107274) panicked at martin-core/src/tiles/postgres/pool.rs:239:14:
container launched: Client(Init(SocketNotFoundError("/var/run/docker.sock")))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This can be solved by several ways according to the testcontainers
crate's documentation.


https://docs.rs/testcontainers/latest/testcontainers/index.html#docker-host-resolution

This pull request adds a few notes about this. I'm not sure if this is a
common issue or not, so please feel free to remove or modify any part
that you feel is a bit too specific!

---------

Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>
Co-authored-by: Frank Elsinga <frank@elsinga.de>